- assets/css/style.css
- assets/js/script.js
- index.html
Contribution: Added a Button in WildGuard
In my recent contribution to the WildGuard open-source project, I implemented a new button feature as per the community's request. This button was added to improve the user experience and enhance navigation within the application.
Feature Added: Button for Scroll To Top.
This contribution helped in making the interface more intuitive and was well-received by the maintainers.
> added scroll to top but with a leaf

- Contact-Us/index.html
- Contact-Us/script.js
- Contact-Us/style.css
- index.html
Related Issue No. (#4)
https://github.com/user-attachments/assets/19a6df7c-64bd-41f3-847b-50893f1f5f9b
> Adding the Separate Contact-Us Page

- assets/css/style.css
- assets/js/script.js
- index.html
Added Search Functionality in Homepage which lets you to find the text you want.Below I am attaching the video for demonstration. and Before and After screenshots for references.
This fixes the issue : #9 
Video:
https://github.com/user-attachments/assets/5896b723-30f3-45d3-b962-a40a3066cf94
---------------------------------------------------------------------------------------------------------------------------
Screenshot Before:
-----------------------------------------------------------------------------------------------------------------------
Screenshots after Fix :
--------------------------
----------------------------------------------------------------------------------------------------------------------------
@anuragverma108 Thank you for the opportunity. I have fixed the …
> Added Search Functionality in Homepage 

- assets/css/style.css
- index.html
small screen navbar issue is fixed  issue #43 
before fixing web was look in tab and mobile screen like this
tab..
mobile md size..
mobile sm size..
now after fixing it
tab..
mobile md size
mobile sm size
> fixing  issue #43 

- README.md
> Project Documentation Improved : Detailed README added

- Contact-Us/index.html
- Contact-Us/style.css
- privacy-policy.html
- terms-of-use.html
**Related Issue:**
- Closes #151 
**🔗 Improve Navigation : Add Back Button to Policy, Terms, and Contact Us Pages!**
This pull request adds a back button to the Policy, Terms, and Contact Us pages, enhancing user navigation by allowing users to easily return to the previous page they visited.
**Changes Made:**
- Added a back button to the following pages:
- Policy
- Terms
- Contact Us
- Ensured the button is styled consistently with the overall design of the website.
**Testing:**
- The back button has been tested on all three pages to ensure functionality, and it correctly navigates back to the previous page.
- Verified that the button is visually aligned with the site’s design.
**Screenshots :**
---
> 🔗 Improve Navigation: Back Button Added to Policy, Terms, and Contact Us!

- assets/css/style.css
> Updated the button

- assets/css/style.css
I have successfully implemented the "Add Box Styling to Navbar Links for Enhanced Visual Appeal" feature on the WildGuard website. The navbar links (Home, About, Services, etc.) now have box styling, which improves visual clarity and contributes to a cleaner, more structured layout. This enhancement aligns with the existing theme of the website, providing a more engaging and user-friendly navigation experience.
Feel free to review the changes and provide feedback!
> Added boxes on nav bar links

- index.html
> Fix vision and next plan button click issue ##16

- index.html
- terms-of-use.html
- Fixes issue #247 
📄 This PR re-adds the "Terms of Use" page after the previous merge (#70) disorganized the site structure. As suggested by maintainer @anuragverma108, the following changes were made:
- Re-added the `terms-of-use.html` file with the correct structure.
- Linked the page in the `index.html` footer/header.
- Resolved conflicts with the latest code from the `main` branch.
- Verified that the "Terms of Use" page now works correctly and doesn't affect the site structure.
- Fixes PR #70
> 🛠️ Re-add Terms of Use Page and Resolve Conflicts (as suggested by maintainer @anuragverma108)

- assets/css/style.css
I have added hover effect on the buttons in about us section.
Resolves #55
> Added Buttons hover effect

- assets/css/volunteer.css
- index.html
- volunteer.html
I have implemented a volunteer registration page as part of the wildlife sanctuary project. The page allows potential volunteers to sign up and provide their details, which will help streamline the volunteer onboarding process.
This pull request aims to enhance the FAQ section of the SkillWise website, which addresses issue #32 
Changes Made:
Added an HTML form to the volunteers.html page.
Styled the form using CSS classes for a consistent UI.
Screenshots:
Before --> 
After -->
Please consider adding the "Hacktoberfest Accepted" label to this pull request to support my participation in Hacktoberfest.
Thank you for considering this PR! I look forward to your feedback.
> Volunteer registration

- assets/css/style.css
- index.html
> Modified leaf icon

- assets/css/style.css
- assets/js/script.js
- index.html
This PR introduces the UI for the login functionality, designed to enhance user experience and streamline the authentication process.
After:
> Added Login Functionality

- assets/css/style.css
- index.html
1. Corrected the "Rise" word to "Raise"
2. Added hover effects on buttons  
https://github.com/user-attachments/assets/be768640-973e-48f7-94a2-8e43fed836b1
https://github.com/user-attachments/assets/50ec6ee0-60f1-4c1f-8c67-7be0bc5fde27
Add on- Should improve the our mission, our vision, next plan interface...a div should be added with slide down animation which will show the content on click. If u assign me I would like to work on it too.
> Spelling mistake corrected and Added hover effects on few buttons #252

- Contact.html
- index.html
Resolve #274 
✨ Re-add Contact Form with Enhanced UI and Green Pistachio Theme 🍃
---
- Reintroduced the contact form on the contact page, following the new design aesthetic of the website.
- Applied the **green pistachio** theme from the website’s palette to match the branding and ensure visual consistency. 💚
- Enhanced the form’s design with user-friendly styling, including smooth transitions and a rounded submit button for better interaction. 🚀
- Fields include **Name**, **Email**, and **Message**, providing a clear and straightforward way for users to contact us. ✍️
- Removed the navbar for a focused user experience on this page.
Screenshots:
Let me know if you'd like to tweak anything!
> ✨ Re-add Contact Form with Enhanced UI and Green Pistachio Theme 🍃

- assets/css/style.css
- assets/js/script.js
- index.html
https://github.com/user-attachments/assets/44bf2b3f-d7bc-4c1b-8e6e-d0595eca1e53
Fixed Translation Options in the header part, now the site it fully functional in all three languages English, Spanish and French
> #144 [FIXED]  Language Options Accessible on Headers

- Donation.html
- index.html
I updated the donation page by linking the donation form, allowing users to easily submit their contributions. I implemented CSS to style the page, enhancing its visual appeal and overall layout. Additionally, I added JavaScript functionality to display a search bar, enabling users to search for relevant information seamlessly.
> updated and linked donation page, and added css and js for displaying search bar

- assets/css/style.css
- assets/js/script.js
- index.html
issue no #145 . Added FAQ section with green hover as part of hacktoberfest2024.  Added 3 questions available on same repository.
Please look into it.  @anuragverma108
> Added FAQ section  issue no #145 

- index.html
Reverts anuragverma108/WildGuard#504
> Revert "contact page re-connected properly"

- assets/css/style.css
- index.html
@PriyaGhosal please merge my pull request
> Fixed the footer aligment and margin

- assets/css/style.css
- index.html
Changed the text color of the email input field in the footer to white.
> Changed email input field text color to white #347

- index.html
Earlier the Contact link was leading us to home, but now it is leading to the end of the index.html page where contacts are provided. Also applied a Search bar.
##before
##after
> Contact Link is working perfectly now

- assets/css/style.css
- contributing.md
- index.html
fixed issue : #113  
Nav Bar :
before :
after :
nav links and about section text alignment : 
before : 
after :
> Fixed nav bar, nav links highlighting, about section text-alignment

- assets/css/style.css
- assets/js/script.js
- index.html
@PriyaGhosal please merge my PR
> Adding progress bar on the top of the page. #125

- assets/css/style.css
- contributing.md
- index.html
Do lemme know if there is something more to be added
...
Thank you for considering contributing to **WildGuard**! We appreciate your interest in making a meaningful impact on animal welfare and environmental conservation. This document will guide you through the contribution process and help ensure that your contributions fit within the project’s goals and guidelines.
- Navigate to the [WildGuard GitHub repository](https://github.com/anuragverma108/WildGuard).
- Click the **Fork** button to create a copy of the repository under your own GitHub account.
- Clone the forked repository to your local machine:
```bash
git clone https://github.com/your-username/WildGuard.git
cd WildGuard
```
- It's a good practice to create a new branch for each feature or fix you're working on:
```bash
git …
```
> Added contributing.md - Patch 1

- index.html
Hi @PriyaGhosal ,
I have reviewed the code and found that there was one missing alt tag for an image. I have added the appropriate alt text ("Decorative design element for styling") to improve accessibility.
Even though it was just one missing alt tag, it's important for overall accessibility, and this fix ensures that the project meets accessibility standards. Please review my changes and let me know if any further adjustments are needed.
Thank you for your time, and I look forward to your feedback!
BEFORE 
AFTER
I have added an alt tag to the decorative image, which is crucial for the website's accessibility. Alt tags ensure that visually impaired users can understand the content of the images through screen readers. This improvement adheres to accessibility standards and enhances the …
> Resolved merge conflicts and added missing alt tag #95

- index.html
Resolved Issue No. #1
There were irrelevant text 
Before:
After:
> Issue #1 Added text to cards in place of irrelevant messages 

- index.html
Hi @anuragverma108, I have
Closed #300 
Closed #198 
As mentioned in the issue, I have added the WildGuard Logo in the footer and removed Terms and Privacy&Policy which was showing twice before. I have also resolved the conflicts and updated the logo in the footer.
If accepted, please accept this PR under Hacktoberfest2024 and please do add hacktoberfest,hacktoberfest-accepted and hactoberfest2024 labels.
> ISSUE #198: Removed Terms of use and Privacy & Policy in footer and added WildGuard Logo in the footer

- .vscode/settings.json
- index.html
initially, "mission" button was active in "about" section as default but the content was something random and also there was no "learn more us" in default setting....
https://github.com/user-attachments/assets/91938a52-5f82-4582-9c26-791188e1541d
https://github.com/user-attachments/assets/b859977a-a3c1-4a62-85ce-6c2c02210a9b
Now, as default :
https://github.com/user-attachments/assets/36d7dff9-67b2-4f6c-aad4-d2cc2bb73e49
https://github.com/user-attachments/assets/8a8c768b-fc7b-4a01-8a7e-740194d0c05c
And a line in home was also disoriented, Now it's not.
please merge and give it the tag "Hacktoberfest accepted"
> default_content_of_about

- assets/css/style.css
- index.html
Issue number: #683 
https://github.com/user-attachments/assets/5958774f-66ad-4737-8f47-2750c90ec21f
Added pop up on hover @anuragverma108 plz review this pr and add hacktoberfest label.
> added pop up

- Contact.html
- index.html
Resolve #688 
---
**Pull Request Title:**
**📬 Add Contact Us Page to WildGuard Website 🌐**
Hello @anuragverma108 👋,
This pull request introduces a **Contact Us** page to the WildGuard website, allowing users to easily get in touch with the support team for assistance or inquiries.
1. **Contact Form Added**:
- Fields included: **Name**, **Email**, and **Message**.
- Designed with Bootstrap for a clean and responsive layout.
2. **Contact Information Section**:
- Added email support: **support@wildguard.com**
- Added phone support: **+91 123-4567-089**
3. **Styling Enhancements**:
- Utilized the **pistachio** and **baby-powder** color scheme to align with the WildGuard design.
- Added hover effects to the send button for a better user experience.
4. **Back Button …
> 📬 Add Contact Us Page to WildGuard Website  In Footer Section🌐

- donate.html
Fixes #679
This update improves the readability of the donation summary by adjusting the colors, making it more accessible for users.
> Improved the CSS of the Donation page for enhanced visibility and readability.

- .github/templates/pull_request_template.md
- index.html
https://github.com/anuragverma108/WildGuard/issues/63
Pull Request Description
Description:
This pull request introduces a Pull Request (PR) template to the project. The purpose of the PR template is to standardize and improve the quality of pull request submissions by ensuring that contributors provide the necessary information. The template guides contributors to summarize their changes, link related issues, include testing details, and provide any relevant screenshots.
Added a pull_request_template.md file under the .github/template directory.
The template includes sections for description, key changes, related issues, screenshots, testing, types of changes, and a checklist for contributors.
Key Changes:
Added: .github/template/pull_request_template.md
Related Issue(s)
No related …
> feat: added pr and issue template

- style_changed.css
<h3>Hover effect added over Select Language</h3>
> Added hover over Select Language to enhance user interface: Ref to issue # 672 

- SaveNature.html
- assets/css/SaveNature.css
- index.html
**The confict part** 
**Before**
**After** 
https://github.com/user-attachments/assets/b030e8a3-2691-4b38-861d-16c3314c4160
commite with the latest upstream task done assign mw iwth appriate level tag
> Added saveNature.html and css and remove the nav bar conflict

- faq.html
Hi  @anuragverma108 
I wanted to inform you that I contributed to building the FAQ page as part of Issue #714. Please review my work and let me know if any further improvements or adjustments are needed.
Looking forward to your feedback!
> FAQ page added

- about.html
- index.html
The issue with the 'Learn More About Us' button has been resolved. It now redirects to a new page where we can add more details about us.
> about issue and about page added #724

- index.html
Thank you, for letting me contribute to the project. I have added the social media link in the project which are redirecting the actual social media sites.
> social media links added #725

- assets/js/script.js
Initially the navbar was not working as expected. On clicking the contact section in navbar, the page was navigating to contact section but it was not reflecting in the navbar. So I fixed that issue. Now navbar is working correctly. Please accept this pull request and merge and attach the label of hacktober-accepted
Before
After
> Fixed working of navbar. Issue #744

- moreevents.html
Solves : #748
I have redesigned the more events page and this is how it looks at the end
> Redesigned more events 

- assets/css/style.css
- index.html
Solved issue #719 
Before:
After:
> Fixed login/register & conflict issues #719

- assets/css/style.css
#754 changed the color of leaf button so it matches the theme of the website.
> Change leaf btn color

- assets/css/style.css
- index.html
we have login and signup popup before some like 
now after making some changes, it looks like 
login 
sign up
> solved #694

- assets/css/style.css
- assets/js/script.js
- index.html
Feature Added: Implemented a modal popup to enhance user interaction. This modal provides additional information about events when the "Learn More" button is clicked.
Before: 
After:
Changes Made:
Added HTML structure for the modal.
Implemented CSS for modal styling.
Created JavaScript functionality for opening and closing the modal.
Issue Reference: Fixes #766
> Add Modal Popup Feature

- SaveNature.html
- assets/css/SaveNature.css
**Fixes:** #773 
**Summary of Changes:**
- Centered the text on the Save Nature page.
- Adjusted CSS styles to ensure responsiveness.
**Screenshots:**
Before: 
After:
> Centered Some Content on Save nature Page

- index.html
added login and register appear separately for better experience.
> Issue #779 login and register should be differently placed

- index.html
Issue- #782
The Close button was not working in view event tile, which causes the user being stuck in the view event tile
Before
https://github.com/user-attachments/assets/e2748178-128f-4280-853c-5a05d461c222
After
The Close button is now working in view event tile, it brings backs the user from where he was before clicking the view event button
https://github.com/user-attachments/assets/9e08eaff-2021-471a-87b8-14b5e7cb7133
> Fixed:- Close button works now in view event tile #782

- donate.html
i have update the code as mentioned in the issue : "receipt to download in PDF after donation #699"
> added download receipt option in donate.html

- terms-of-use.html
Hello @anuragverma108 
I have updated the UI of term of use page and added the dark mode in this page please check it and merge it under the Hacktoberfest 2024 label .Hoping to get it merge I have resolve the conflicts as well please check.
Regards
Dhruv Johri
> Updated Term of use page #644

- terms-of-use.html
Reverts anuragverma108/WildGuard#769
> Revert "Updated Term of use page #644"

- index.html
I added a Frequently Asked Questions section in index.html and ensured the content aligned with your project guidelines.
> Add accordion section in index.html

- about.html
- assets/css/style.css
- index.html
before the solving nav pages was looks like on small screen
tab
mobile medium screen 
mobile small screen 
after solving the issue now it's look 
tab
mobile medium
mobile small
> nav pages on small screen  visibility solved 

- assets/css/style.css
- index.html
Mine issue is #813 . In the donate section, the amount was not logically correct. There were issue with it. Total donation amount was not equal to the amount donated and amount still needed to raise. Also the progress bar was not showing the correct percentage. I have done the changes and made it correct.
Please accept this PR and merge with the label hacktoberfest-accepted under hacktoberfest 24
Before making the contribution: 
After making changes:
> #813 corrected the donate section

- assets/css/style.css
…r visibilty.
Line 2195- Changed color to bright yellow crayola again for better visibility throughout the webpage. Line 2199- Changed the color to pistachio_100
Before-
After-
> (issue #825) LIne 478- Changed color from white to bright yellow crayola for better visibility

- assets/css/style.css
- index.html
**ISSUE -  #757 **
I have added the changes and enhanced the marquee in the insta-post-section .
Please have a thorough look at the video and then decide before closing it  .
https://github.com/user-attachments/assets/bcabe35a-8292-4522-a266-4d34a6b31060
> added changes and marquee for the insta-Post-section

- assets/css/style.css
- feedback.html
- index.html
I have added a feature for user feedback.
> feedback page added(Issue #625)

- assets/css/review.css
- assets/js/review.js
- review.html
This PR addresses issue #795, focusing on enhancing the user interface of the Review Page. The updates aim to improve user experience, readability, and visual appeal.
**Fixes:#795**
**Key Improvements:**
- Simplified Layout: Streamlined the review layout for better readability and reduced clutter.
- Typography: Updated font sizes and styles for enhanced legibility.
- Color Scheme: Introduced a more harmonious colour palette to improve visual appeal.
- Responsive Design: Ensured the review page was fully responsive and adaptable to various screen sizes.
**All Features**
**Rating System Features**
- Compulsory Rating: Ensures a minimum rating of 1 star is selected before submitting.
- Rating Validation: Validates user input to ensure a rating is provided.
- Automatic 1-Star …
> Improve Review Page UI #795

- assets/css/style.css
- index.html
Updated the feature items by adding a glowing effect and upward movement on hover to enhance user interaction. This change improves the overall user experience, making the UI more user-friendly. Please review and consider accepting this pull request.
> Updated the Feature item by adding a glowy effect on hover

- SaveEcology.html
- index.html
This pull request introduces a new Save Ecology page to the project. The page has been fully integrated with both HTML and CSS to provide an appealing and functional design, promoting ecological awareness.
Key Updates:
SaveEcology.html:
- Created a new HTML file (SaveEcology.html) that serves as the foundation of the Save Ecology page.
- This page contains various sections aimed at encouraging environmental preservation and outlining steps for individuals to contribute towards ecological sustainability.
- Includes a header with navigation links, section blocks with informative content, and a contact form for user engagement.
- Emphasizes the importance of ecology through clear and structured content, including a statistics section that visually highlights key ecological data.
Request for …
> Integrated Save Ecology html and css pages

- index.html
- login.html
This JavaScript code is designed to enhance the mobile navigation experience on your website. When the page loads, it sets up functionality for the menu buttons.
Listening for Page Load: The DOMContentLoaded event ensures that the code runs only after the entire HTML document is fully loaded, so everything is ready to interact with.
Selecting Elements: It selects the elements that control the navigation:
The button to open the menu (navOpenBtn).
The button to close the menu (navCloseBtn).
The navigation menu itself (navbar).
Opening the Menu: When the user clicks the open button, the code adds an "active" class to the navbar, making it visible on the screen.
Closing the Menu: Conversely, clicking the close button removes the "active" class, hiding the menu again.
> Making the menu collaspe button work by writing jscode and debugging it

- Become-a-Partner/style.css
- index.html
- style_changed.css
Changed Button Sizes Font size inside and Box shadow in Webpage to clear visible and good looking
> Changed Button Sizes Font size inside and Box shadow in Webpage

- index.html
I have successfully added hover effect.
> hover effect added #902

- assets/js/carousel.js
- assets/js/script.js
- index.html
#909 added an alert option on clicking submit in the share your thoughts forum as the user might not be certain if it got added or not 
i would request you to merge this as it would be of a great help for the user.
> #909 added an alert on clicking submit in the share your thoughts forum 

- TreePlantation.html
- assets/css/TreePlantation.css
- index.html
#913 added a complete clone website of save nature for tree plantation which has information about the tree plantation drive 
https://github.com/user-attachments/assets/a7bc63dd-ec77-4211-acfc-4eee799156ac
i would request you to merge this request as it is very useful for the website and is a huge change as it creates a new website that is also a clone of save nature hence providing symmetry between its branch websites .
> #913  added a website on tree plantation in its readmmore option which is similar to save nature website

- assets/css/style.css
- index.html
Now it's better than before : 
https://github.com/user-attachments/assets/447bbe7c-8b87-4e8d-a6b1-967e6278a634
Kindly merge it.
> #fixes issue #950 improved_search_button_and_removed_unnecessary_logo

- assets/css/style.css
I have added some styling in search bar in navbar section which looks good as compared to before. Therefore accept this changes under the hacktober fest 2024
> Added some styling on search bar  #971

- moreevents.html
Closes: #890
This pull request introduces the following changes for the **Events Page**:
- **Implemented a responsive and interactive grid layout** to display both **future** and **past events**.
- The grid dynamically adjusts for different screen sizes:
- **1-column layout** on smaller screens, ensuring no overflow or layout-breaking issues.
- Added **smooth animations** to the event cards, making them "slide in" when loaded or resized, enhancing the user experience.
- Separated the events into two sections:
- **Future Events**: These events include a "Book Now" button with hover effects for booking tickets.
- **Past Events**: Displayed without a booking button, just showing the event details.
- Improved **hover effects** and styling of the event cards and buttons to increase …
> More Events page rebooted with BETTER UI #890

- assets/css/style.css
- index.html
I have added the simple contact us form with some field like name , email, message. Also give me more instruction about this component.
> Changing ui of Contact Us page and its working. #751

- about.html
- assets/css/about.css
Issue : #1001 
Enhanced the about page with more details and much better UI.
Before: 
After:
Happy Hacking!
> [Enhancement] Enhanced about page

- index.html
issue - #1007
before
https://github.com/user-attachments/assets/570fd2ed-bc74-4c51-9193-48bc26a0384a
After
https://github.com/user-attachments/assets/5d50515f-75e9-4b9b-bb6d-0c5fb2ee3989
> fixes- #1007 Cross not working in view event tile

- assets/css/register.css
- register.html
This PR addresses Issue #1006 by introducing a redesigned Register page UI, focusing on clarity, simplicity, and visual appeal.
**Changes:**
- Updated layout for improved readability and reduced clutter
- Implemented consistent branding and colour scheme
- Improved mobile responsiveness
- Added Home button for easy navigation to the homepage
- Enhanced Sign with Google and Facebook buttons for streamlined social authentication
- Improved button design and layout
- Optimized for mobile devices
Before-
After-
**Checklist:**
> Enhance Register Page UI

- style.css
> Fixes- #1019 Improved the Impact of UR donation UI

- cleanocean.html
- moreevents.html
#1023  added the registration for event under clean our ocean card (in more events) as clicking on it led to no where before 
https://github.com/user-attachments/assets/c857dc75-0801-4c53-924a-27ede9c039cb
the new registration website is well designed and is requested to be added as people might be interested in registering for events
> # 1023 added the registration for event under clean our ocean card (in more events)

- assets/css/login.css
- login.html
BEFORE
AFTER
I added hovering effects such as better color changing and scaling of buttons and made the green color even more better
> Added my changes for login.css

- assets/css/style.css
- index.html
Reverts anuragverma108/WildGuard#1046
> Revert "UI improved wildlife conservation forum "

- index.html
Reverts anuragverma108/WildGuard#1035
> Revert "Resolved Issue For btn-top-Funtionality"

- faq.css
- faq.html
I saw your page it is only FAQ page not in style for that i take over it and i changed it to better user experience like font-size , aligning items , font-family and b-g color and font-weight
BEFORE : 
AFTER :
> FAQ's modification looks better after this for User experience

- assets/css/style.css
Reverts anuragverma108/WildGuard#1056
> Revert ""Our Testimonials" Text Not Visible Due to Color Contrast - Issue #1054 Resolved"

- SaveEcology.html
- SaveNature.html
- SaveOcean.html
- TreePlantation.html
The links which are not working in the footer of the pages like Save Nature, Save Ecology etc.,  are now working according to the main page of the website.
This are  now changed into ;
> The links issue has been solved

- SaveEcology.html
- SaveNature.html
- SaveOcean.html
- TreePlantation.html
Reverts anuragverma108/WildGuard#1058
> Revert "The links issue has been solved"

- style.css
#1063 Fixed unusual scaling of support us cards on hovering
> #1063 fixed Support us cards

- index.html
- user.html
This update introduces a new user page that is now accessible when the user clicks on the user icon in the header. The user page displays relevant user information and enhances the navigation experience for logged-in users.
Created a new user page.
Linked the user icon to the user page for seamless redirection.
Ensured smooth navigation and proper layout integration.
Issue #1073
> Linked User Icon to New User Page

- assets/css/style.css
- index.html
fixed #905 
- Enable the function of Hamburger Icon.
- I made some changes to the Navbar because the content was overflowing.
- Gave the proper Indention to the elements of Navbar.
- Correct the misalignment of the User Icon.
> Please check, I have resolved the Conflicts raised in the Navbar.

- assets/css/style.css
#1084 
After :- 
before:-
@rahulkhandait-sde
> Fixed the alignment of search button

- CODE_OF_CONDUCT.md
> Added CODE_OF_CONDUCT.md file to the repository

- Contact.html
- assets/css/contact.css
Issue #1088 
Enhanced the contact page with much better UI.
Before: 
After: 
Happy Hacking!
> [Enhancement] Redesgined contact page

- index.html
updated index.html, and now has the option to redirect to home page when clicked on the logo
> Redirects to home page when logo is clicked

- index.html
Changed the cursor icon to a clickable cursor icon in the tree plantation service card in the service section.
Fixes: #1097
> Fixed cursor display bug

- assets/js/script.js
- index.html
Added a feature for the logo of wild guard n the navbar so that when  it is clicked it is redirected to the home page
couldnt take a screenshot
> adding the logo of the wild guard a feature of retrieving back to home when it is clicked

- assets/css/SaveNature.css
- index.html
- login.html
In the navbar of the homepage, the login button was not working, i.e. it is not redirecting to the login page. This issue is handled.
Styling of the footer of saveNature page is added
> Added Navlink to the login section in the homepage #1122 and Styling footer of saveNature page #1134

- assets/css/style.css
- index.html
> Issue 1117 Making cards flippable updated

- index.html
- style.css
Issue Number: #1153
Added a dropdown that appears when hovering over the profile picture.
Dropdown contains options for "Profile" and "Logout".
tested the changes for responsiveness and usability.
Before:
After:
> Added profile hover dropdown for profile and logout options #1153

- assets/css/style.css
- index.html
- learnmore.html
- styles.css
#1165 added a website that gives more information about the success stories, how donations help , etc
https://github.com/user-attachments/assets/11244dbe-36de-4806-a1a2-1e25669d2a76
it would be of great help for the user interested in learning more about the noble cause of this website therefore it is requested to add this change in your website and merge this pull request.
> #1165 added a website which give insight about the cause of this website on clicking the learn more button

- about.html
- assets/css/about.css
Issue_Fixed_From_My_Side # 613
#613 
hi , I updated the about us section pls verify and accept my pull request
> Add contact us/#4 updated

- assets/css/style.css
- index.html
- style_changed.css
**fixed image preview size in Donate Section**
**fixed CSS in this website**
**improved the responsiveness of the website**
**arranged the code and removed extra unwanted codes**
> fixed the image size in donate section and corrected some CSS #1111 #1141

- assets/css/style.css
- index.html
Hi @anuragverma108 | @PriyaGhosal 
- Issue fixes #1138
I have added the scroll down progress matched to the website design theme
https://github.com/user-attachments/assets/f91c9a0c-1f14-4140-b498-e03e008da3e7
could you please review it?
Thank you!
> Added a Scroll Down Progress Bar Matched to the Website Design Theme 

- assets/css/style.css
- index.html
Issue no. 1191
the icon and the read more buttons were scattered and flowing and I fixed that issue.
Before the fix
After the fix
If the fix seems good please merge it. 
Thank You.
> made the design of the service cards consistent and fixed overflowing

- assets/css/style.css
- index.html
Reverts anuragverma108/WildGuard#1194
> Revert "made the design of the service cards consistent and fixed overflowing"

- index.html
- style.css
- styles.css
- stylesss.css
Status : Resolved 
Home Page :
Before : 
After: 
https://github.com/user-attachments/assets/31fe480c-43cb-492a-8375-a2fe9c054843
Donate Section->
Before : 
After :
Learn more button : 
Before: 
After :
View Events :
Before : 
After : 
More Event button : 
Before : 
After :
> Improved button UI for 'Learn More,' 'Donate Now,' and 'See Event'  #1250

- WildGuard-main/index.html
Please merge this under **HacktoberFest2024 !**
Work done : Hover on navigation -" Login & Register" was not working I added the hover effect.
and now on hover the text size increases by 1.5rem.
PR-#1207
Before :
> Hover Effect Added !

- assets/css/donate-form.css
- assets/js/donate-form.js
- donate.html
Issue: #1175 
Before:
<table>
<tr>
<td><img width="1000" alt="Screenshot 2024-10-16 at 2 58 43 AM" src="https://github.com/user-attachments/assets/306c03a5-dad8-448e-aca6-078bd48129a2"></td>
<td><img width="590" alt="Screenshot 2024-10-16 at 2 59 17 AM" src="https://github.com/user-attachments/assets/c80f84d0-d808-4439-a556-292af8022227"></td>
</tr>
</table>
After:
<table>
<tr>
<td><img width="1000" alt="Screenshot 2024-10-16 at 2 59 52 AM" src="https://github.com/user-attachments/assets/3a9d2a92-622c-48b4-a1b9-f48a86f1037b"></td>
<td><img width="590" alt="Screenshot 2024-10-16 at 3 00 46 AM" src="https://github.com/user-attachments/assets/fd0f892e-6505-4a16-9e6c-d64738965acb"></td>
</tr>
</table>
Happy Hacking!!!
> [Enhancement] Redesign Donation form and Greatly Improve the Downloadable Receipt

- assets/css/style.css
I have improved the alignment of donation cards
Before
After
> Improved the alignment of donation cards #1232

- style.css
I fixed the alignment issues inside donation cards by adding minimum height for a section called Benefits.
> Fixed donation card button alignment

- Events-Data/modal.css
- SaveEcology.html
- SaveOcean.html
- TreePlantation.html
- about.html
- index.html
Issue NO : # 1236
updated UI : 👍 
Video 👇👇
https://github.com/user-attachments/assets/222daa26-6fbf-4c9e-9e6d-1792d62f3fc3
this is the updated UI
> Enhanced UI issue No #1236

- index.html
Hii @anuragverma108 !
I have added some more questions in the FAQ's section. It would help the user of our platform for better understanding. Like what to do in the payment failure etc and stuffs like that. It would bring more trust in the user and they would be more likely to donate in our project of saveGuarding wild animal.
Accept this PR under the hacktoberfest and hacktoberfest-accepted label.
Thankyou .
> Added the few questions in FAQ section #1237

- user.html
issue #1245 is fixed with all the needed buttons and addition (AFTER SCREENSHOT)
> user profile updated (issue-#1245)

- Contact.html
The Contact Us page has been optimized for mobile and tablet devices. It now features a fully responsive layout, ensuring seamless usability and proper display on smaller screens. All elements, including the form and images, adjust dynamically for an improved user experience across devices.
fixes #1222
> Mobile and Tablet View: Contact Us Page Now Fully Responsive#1222

- assets/css/style.css
- index.html
https://github.com/user-attachments/assets/e38edeec-4c4e-4325-b4a8-5e5331196fb7
https://github.com/user-attachments/assets/9c2e50ce-d5a6-4196-9e84-a4e601a578e9
> Hover effect successfully added to Login & Register Buttons

- assets/css/style.css
- review.html
**Before**
**After**
- Here i have Changed the UI of the form.
- it is of similar theme as of your website.
> Fix: Issue #1141 fixed the form and its appearance

- assets/css/style.css
This PR fixes issue where the user icon on the navbar was oversized and appeared oval in shape. The problem negatively impacted the visual appeal of the navbar and user interface. This pull request introduces the following changes to ensure the user icon is properly sized and perfectly rounded.
The user icon has been adjusted to be fully circular by setting the border-radius to 50%.
The icon size has been optimized to ensure the icon is appropriately sized within the navbar.
Chrome, Firefox, Safari ,Edge
The icon displays correctly as fully circular across all tested browsers.
[ x ] Code follows the style guidelines of this project.
[ x ] The issue #1273 has been fully addressed.
[ x ]  Changes have been tested in various browsers and screen sizes.
> [fix] Navbar User Icon Rounded and Resized (#1273)

- learnmore.html
#1288 it is requestion to add this change as it might help users interested in donation
https://github.com/user-attachments/assets/7071c589-0745-4697-b40b-853ef1c8dded
> #1288 added the donation website on clicking donate now in the learn more website

- index.html
- login.html
There was a extra toggle icon showing on login page it is now removed.
> fixed the toggle button bug

- .github/templates/pull_request_template.md
- index.html
- register.html
- style.css
@anuragverma108 
Thank you for informing me that ,,
I have added what I have done in pull_request.md in .github /template .
I hope that helps.
Thank you , looking for further contribution for the repo...
> Updated Branch With Current Branch

- index.html
- stylesss.css
Status : Resolved
Submit Button
Before: 
After : 
https://github.com/user-attachments/assets/5164fd5b-afda-4096-96ef-a56dfba1a76d
> Center the Submit Button to Improve UI Interactivity #1276

- assets/css/TreePlantation.css
I have added a animated hover for the navbar in TreesPlantation.html page, and i have also created a border box animation for all the boxes in the page
> Enhanced the ui in TreePlantation.html page

- about.html
On Website under About Us section('OUR CORE VALUES') - Adding transition effect on images.
> Transition effect for 'Our Core Values' in About Us(about.html)

- assets/css/searchbar.css
- index.html
Improved search bar user interface with the below changes latest changes already pulled .
Before:
After:
This pull request closes #1167
> fix: improved searchbar user interface in navigation bar

- assets/css/style.css
- index.html
I have improved the UI and Alignment of about us section, added hover effects on button, added more paragraph text, changed the alignment of buttons
Before - 
After -
> Improved the UI of about us section for issue #1344

- assets/css/style.css
- index.html
- style.css
> Styles: add padding around feature list | add margin in donation button

- assets/css/style.css
- index.html
- style.css
Reverts anuragverma108/WildGuard#1389
> Revert "Styles: add padding around feature list | add margin in donation button"

- assets/css/register.css
- register.html
Fixes : #1349
I fixed the validation of password and email fields and also improved the UI.
> Fix validation of input fields in sign up form

- review.html
Hello @anuragverma108 @rahulkhandait-sde 
I have updated the rate us page #1328 please merge it under the hacktoberfest 2024 label so that it is counted as a contribution hoping to get it merge asap.
Regards
Dhruv Johri
> Updated the Rate Us Page #1328

- login.html
I have done some basic styling to the login page. The images that i wanted to do are not possible since your repo is in a  very bad shape in the sense of pathing so i hope you like what i have done:
AFTER:
BEFORE:
> Changed Styling of the login page

- index.html
- style.css
<a href="https://github.com/anuragverma108/WildGuard/issues/658">Issue #658</a>
added a "Go To Bottom Button" for easy navigation.
>before
>after
> Added Go To Bottom Button

- index.html
- style.css
- style_changed.css
UI of "our testimonials" section is updated
Before:
After:
Please merge this PR
> Our testimonials UI updated #1371

- index.html
- style.css
- style_changed.css
Reverts anuragverma108/WildGuard#1376
> Revert "Our testimonials UI updated #1371"

- Contact.html
- disclaimer.html
- dmca.html
- index.html
Issue resolved successfully #1112 
**Add the DMCA and Disclaimer pages to the header of the site**
Before:
After:
**Add the DMCA and Disclaimer pages to the footer of the site**
Before:
After:
**Add the DMCA and Disclaimer pages at the Contact Us page**
Before:
After:
> Created the DMCA and Disclaimer Pages 

- assets/css/searchbar.css
- assets/js/search-index.js
- assets/js/search.js
- index.html
This PR addresses the need for a search feature on the website.
Changes:
- Added search-index.js to store searchable content
- Created search.js to handle search logic and result display
- Integrated search bar into the header in index.html
- Styled search bar and results in searchbar.css
The search feature now allows users to:
- Enter search terms in the header bar
- View matching results in a dropdown
- Click results to navigate to relevant sections/pages
Testing:
- Tested on Chrome and Brave
Closes #1404
> implemented the search functionality

- index.html
- style.css
- style_changed.css
I have updated the UI of Wildlife Conservation Forum
Before:
After:
Please merge this PR
> UI of Wildlife Conservation forum updated #1369

- Donation.html
1. Better Layout: The donation options and related information could be organized more clearly to make the process more intuitive.
2. Stronger Call-to-Action: The "Donate Now" buttons should stand out more to guide users and encourage engagement.
3. Overall Design: A more polished and cohesive design would improve readability and help users navigate the page with ease.
> UI Improvement Suggestions for Donation Page #1401

- Loginpage.html
Feature Added:
I have added the UI for Social Login options (Google, Facebook, Twitter) to the authentication page.
Changes Made:
Added buttons for Google, Facebook, and Twitter login in the UI.
Styled the buttons using CSS to match the overall design.
Added placeholder JavaScript functions that trigger an alert for each button, which can later be replaced with actual OAuth integration.
This PR focuses on adding the UI only for social logins. The actual integration of OAuth authentication (Google, Facebook, Twitter) has not been included.
Let me know if further adjustments are needed.
> Social Login options added #1391

- assets/css/style.css
Added a better-looking hover effect and made the text bold
> Improved Hover effect of become a partner button.

- EcoFriendlyShop.html
- index.html
- style.css
> Added a new feature -- " Eco-Friendly Shop"   Issue No.---#1488

- style.css
This PR addresses the alignment issue of the arrow within the scroll-to-bottom component as discussed in issue #1430. The arrow was previously misaligned inside the circular div, leading to an unbalanced and less user-friendly interface.
Adjusted the arrow's alignment by implementing Grids to ensure the arrow is centered within the circular div.
Tested the component across various screen sizes and browsers to ensure consistency.
Ensured the component remains reusable by maintaining scalable padding and margins, so it can be used elsewhere on the site without modification.
The corrected alignment enhances the visual appeal and usability of the component, providing a more intuitive user experience.
Fixed Issue #1430 
Browsers Tested: Chrome, Firefox, Safari ,Edge
[ x ] Code readability and …
> [Fixed]scroll-to-bottom arrow alignment (#1430)

- login.html
- login.js
- Created a seperate login.js file containing the logic.
- Add Api-key to make it functional.
> added google login functionality to login page add api key

- assets/css/style.css
Added spacing between textarea in conservation forum. Also fixed hover color on Submit button of this forum
> Added spacing between textarea in conservation forum #1426

- assets/css/style.css
- index.html
Fixes:  #1451
I have updated the services card in the index.html. Initially the button too was getting rotated, hence clicking the button was impossible. I have fixed that
Before:
https://github.com/user-attachments/assets/26f76e63-5b0b-4e2f-9469-5d85cda2ce31
After :
https://github.com/user-attachments/assets/39e23114-a00a-4665-8d0f-1ebaff38d325
> Updated the services cards in index.html

- donate.html
<a href="https://github.com/anuragverma108/WildGuard/issues/1411">Issue #1411 </a>
Earlier the page looked a bit dull. I tried to improve it's looks and make it more appealing.
>before
>after
> improved the looks of the donation page

- user.html
This pull request enhances the user profile page with the following improvements:
-Profile Completion Progress Bar:
Added a visual progress bar to indicate profile completion.
New CSS styles for .progress-container, .progress-bar, and .progress.
-Tabbed Content:
Implemented a tabbed interface with "About", "Badges", and "Activity" sections.
Added styles for .tab, .tablinks, and .tabcontent, along with JavaScript for tab switching.
-Reorganized Content:
Moved "About", "Badges", and "Activity" into separate tabs, improving organization and reducing scrolling.
-Styling Improvements:
Updated styles for the badges section and adjusted existing styles for the new layout.
-Responsive Design:
Ensured all elements are responsive for smaller screens.
These changes aim to create a more organized and …
> Improved UI for profile page  #1448

- index.html
- style.css
Improved the UI of the "Share your thoughts section"
BEFORE
AFTER
> Improved the UI of the "Share your thoughts section"

- assets/css/style.css
- style.css
- style_changed.css
The font of the anchor tags in the navbar is changed and the text on the cards(eg. safe shelter, environment etc.) in the welcome page is set to center. #1432
> CSS of the navbar and the cards is increased

- styles.css
Made page responsive for all devices
Before:
After:
Fixes #1441
Pls accept this under Hacktoberfest2024.
> Fixes #1441 : Made Learn More page responsive 

- assets/css/style.css
- index.html
- style.css
This PR addresses the following UI issues for a more consistent user experience:
- Centered the hero section subtitle across all screen sizes.
- Adjusted the placement of the "Impact of Your Donations" gallery above the FAQs section.
- Added margin-top to the donation button for better spacing.
Fixes #1446 (issue number)
---
- **Before**:
- **After**:
- **Before**:
- **After**:
- **Before**:
- **After**:
> fix: align hero subtitle, adjust gallery position, and improve donation button spacing

- service.html
Fixes : #1429 
Adde the  internal CSS to service page , along with mobile responsive
Image
> fix : added css to service page

- copyright.html
Related Issue:
Implements the new design for the WildGuard copyright policy page as discussed in issue #1495.
Changes Made:
Implemented a new responsive layout with card-based sections.
Added hover effects and animations for interactivity.
Created custom styling for lists and highlight boxes.
Implemented a fixed header with the logo and a footer with copyright information.
Integrated a new color scheme and typography.
Added responsive design breakpoints.
Screenshots:
Before:
After:
> Implement Enhanced Copyright Policy Page Design #1495

- login.html
This pull request enhances the UI of the login page.
Improved the design of the register.html page by adding better styling for a modern look.
Updated the CSS for more responsive layouts.
-Added hover effects at each logos
-Animation effect while visiting the page
Added enhanced form validation for password strength and matching.
Testing:
Tested on Chrome, Firefox, and Edge.
The form works as expected with visual improvements.
UI BEFORE:
UI AFTER:
> Enhanced Ui for login.html

- SaveOcean.html
This pull request introduces significant enhancements to the user interface of the  get in touch form. The changes aim to create a more appealing and user-friendly experience .
**Key Changes:**
**-** Visual Improvements: Updated the layout and design elements to create a cleaner and more modern look.
**-** User Experience Enhancements: Simplified the form fields and layout for a smoother user experience.
**Before:**
**After:**
> Enhance UI of get in touch  form in the saveOcean page (#1502)

- WildGuard-main/Donation.html
Here’s the text with emojis added to enhance engagement and clarity:
Here are the enhancements made to the HTML and CSS for the donation form:
HTML Enhancements
Semantic Structure: Organized the form elements with clear labels and placeholders for better accessibility and user experience. 📋
Form Elements: Added appropriate input types (e.g., number for donation amount, email for email address) to enhance validation and user input. 🔢✉️
Checkbox for Anonymity: Included a checkbox option for users to choose to donate anonymously. 🤫
Button: Used a <button> element for form submission for better semantics and accessibility. ✅
CSS Enhancements
Background Image: Set a full-screen background image with properties to cover and center it, creating a visually appealing backdrop. 🌅
Container Flexbox: …
> UI upgrade for donation form registration page

- aboutus.html
- assets/css/style.css
I have updated the about us page UI and created a new file for this for comparison. For now,  I have fixed the following:
- navigation bar
- removed the 'main' at the top of navigation
- match UI / UX to the home page of WildGuard
Before:
Proposed About Us page:
> new about us ui home page #1402

- index.html
Validation fix for footer subscribe input and added required paramter
> Footer subscribe input validation fix #1519

- index.html
Issue No:   #1539 
New Feature : Implementing "Animal Rescue Statistics " Which Shows info about how many animals saved this Year!
https://github.com/user-attachments/assets/c8b43630-dd1d-45a3-9571-af419d79b8da
> New Feature : Implementing "Animal Rescue Statistics " Which Shows info about how many animals saved this Year!

- WildGuard-main/index.html
- WildGuard-main/nav.css
just tried to change lil bit of navigation bar as i  m a beginner
> nav bar design change #1526

- privacy_policy.html
enhanced privacy policy section by providing additional information like "how do we collect user data", "how do we protect and share and protect your information".
> enhanced privacy policy

- login.html
- login.js
- Added the facebook login logic for login page in login.js file.
- Add Facebook app-id to make it functional.
> added functionality to facebook login btn add appid

- EcoFriendlyShop.html
- WildGuard-main/assets/js/script.js
- WildGuard-main/index.html
- index.html
🚀 Fixed the color changing issue of navbar-link options, now while clicking onto the navbar-link options it will scroll down and  will change its color default to pistachio.
***
_Here, attaching the before and after changes_
https://github.com/user-attachments/assets/90be1b68-c4e4-46d1-b1d3-f5415630c430
https://github.com/user-attachments/assets/7ec276a8-c76e-4d73-83d5-1ba5f19022ad
> Fixed delayed color changing of navbar options while toggling

- Contact.html
https://github.com/user-attachments/assets/e4c6b336-5503-4ff8-bb93-c6232e187e78
> Added tooltips in the contact form

- WildGuard-main/assets/css/style.css
- WildGuard-main/donate.html
- WildGuard-main/index.html
- WildGuard-main/style.css
Changed the donation button's colour from red to white while hovering and also text to green. #1544
> Updated donation button on home page while hovering 

- Donation.html
<a href="https://github.com/anuragverma108/WildGuard/issues/1444">Issue #1444 </a>
I created an Alert Box as confirmation for submission of donation.
>Before
>After
> Created an Alert_Box when "Donate Now" is pressed

- index.html
- style.css
issue #1408 fixed 
previous screenshot
current screenshot
> wild conservation form updated 

- assets/css/style.css
- login.html
- login.js
before :
after:
Current Behavior
Light background with high contrast colors
Bright white backgrounds for containers and inputs
High contrast between text and background
Bright green gradient in the background
Proposed Changes
Implement dark mode color scheme
Reduce overall contrast while maintaining accessibility
Replace bright background with dark gradients
Update form elements to match dark theme
Modify social login buttons for dark theme compatibility
Update shadows and hover effects for dark environment
Adjust text colors for better readability in dark mode
> Dark Theme Implementation for Login Page #1612

- assets/css/style.css
- login.html
- login.js
before :
after:
Previously, the carousel and footer sections were directly adjacent, resulting in a visually compressed layout with minimal separation between these elements. To enhance the overall user experience and ensure visual clarity, a margin-top of 1rem was applied to the carousel container. This adjustment improves content flow by creating a defined buffer zone between the dynamic imagery of the carousel and the footer section, which houses essential navigation and subscription links.
The added spacing not only contributes to a cleaner UI but also aids in establishing a clear structural hierarchy on the page, drawing attention to the core content in the carousel while maintaining accessible footer navigation. This update aligns with responsive design principles, as the margin …
> Added Margin-Top Between Carousel and Footer for Improved Spacing

- assets/css/style.css
- index.html
- login.html
- login.js
- style.css
before :
after :
This PR addresses the need for an improved user experience (UX) within the Wildlife Conservation Forum by revamping the forum container's design. The enhancements include modifications to the container's width and overall styling, optimizing visual hierarchy and maximizing available screen real estate.
Changes Made:
Increased Container Width: Adjusted the forum container’s width to ensure a more spacious and responsive layout, enhancing readability and user engagement. The expansion maintains an adaptive grid to ensure the container scales effectively across diverse viewport sizes.
Enhanced UI Aesthetics:
Added refined padding and margin configurations to achieve a balanced composition, ensuring consistency with WildGuard’s design language.
Upgraded color scheme and …
> Enhance Forum UI by Expanding Width and Improving Visual Design

- assets/css/style.css
- index.html
- login.html
- login.js
- style.css
before :
after: 
In this pull request, the UI of the user profile page has been significantly improved to create a more visually appealing and user-friendly interface. The key changes include:
Responsive Design: The layout and elements are now optimized for both desktop and mobile screens, ensuring a consistent and accessible experience across devices.
Improved Aesthetics: The profile picture, name, and job title are now presented in a clean, centered layout, creating a more polished and professional appearance.
Informative Metrics: The user's follower, following, and post counts are now prominently displayed, providing quick insights into their online presence and engagement.
Engaging Interactions: The social media icons and "View More" button encourage users to further explore the …
> BugFix : Proper allignment in UI of users card of users.html endpoint

- assets/css/contact.css
- assets/css/login.css
- assets/css/register.css
- assets/css/review.css
- assets/css/style.css
- index.html
Little bit in the UI of website's background
> Change in Background UI

- WildGuard-main/index.html
styled the wildlife conservation forum, Changed the colour of the submit button which now looks compatible with the theme used in the website.
> Did some styling on Wildlife Conservation forum now it looks perfect #1556

- assets/css/review.css
- assets/js/review.js
- review.html
This PR introduces an improved feedback rating system that replaces the previous slider with a star-based rating UI. The changes make feedback submission more intuitive by enabling users to select a rating by hovering and clicking on stars. Additionally, the visually unappealing slider below the feedback form has been removed for a streamlined look.
Changes Implemented
Star Rating System:
1. Added functionality to display a hover effect on stars up to the selected rating.
2. Allows users to click to set a rating, which is visually confirmed by highlighting stars.
3. Real-time display of the selected rating value to improve user feedback.
UI Clean-Up:
1. Removed the slider element under the feedback form to enhance form clarity and focus on the star-based rating.
Before:
After:
> Enhance Feedback Rating System with Star Hover & Remove Slider

- style.css
Issue is fixed, text is visible now.
before
After
> Fix issue #1684 Text is not visible
