anuragverma108/WildGuard

- assets/css/style.css
Previously it was like this with no hover effect
After
@anuragverma108 please review this pr.
> Add hover effect on `Become a partner` Button

- assets/css/style.css
#667 
added background to nav menu on hamburger when screen size get smaller 
so that it wont be hidden on white bg.
> fixed menu bg on small screen

- assets/css/style.css
Resolves layout issue causing blank space before progress bar.
**Fixes - #704** 
**Changes:**
Adjusted CSS styling for the progress bar container to remove unnecessary space.
Here is the updated progress bar -
**Testing:**
Verified fix on Chrome (Version 129.0.6668.90), and Windows 10.
Checklist:
> Fix Progress Bar Layout Issue

- index.html
- moreevents.html
Previously
learn more us button not working
Now
it directs to new page where other more events are present.
> Added new moreevents page and fixed more event button in index file

- index.html
This pull request addresses the issues outlined in #736 by implementing the following changes:
- Updated the copyright text to include the proper copyright symbol (©).
- Removed the "Terms of Use" and "Privacy Policy" links from the quick links section to eliminate redundancy.
- Improved alignment and spacing at the bottom of the footer for a cleaner look.
Before: 
After:
> Bottom Footer and Redundant Links

- assets/css/style.css
#755 changed the alignment of subtitle.
> changed alignment

- index.html
Issue Addressed: Users were unable to navigate to the registration page when clicking the "Register"
link in the navigation bar.
This implementation ensures that the registration link works as intended and improves the user experience by directing them to the correct page upon clicking the link.
Testing:
Click the "Register" link in the navbar to confirm it successfully redirects to the registration page without any issues.
> Fix Redirect for Register Link

- copyright.html
current third party content section states :
"WildGuard may include links to third-party websites or display third-party content. We are not responsible for the content, copyright policies, or practices of third-party sites."
Request to approve the change of above content to :
"
WildGuard may include links to third-party websites, display third-party content, or incorporate services
provided by third-party entities. We provide these links and content for your convenience and information.
However, we do not endorse, control, or assume any responsibility for the content, accuracy, privacy policies,
copyright policies, terms of service, or practices of these third-party sites or services.
"
Thanks,
Maninder
> Update copyright.html in the third party content section

- assets/css/style.css
- index.html
> searchbar properly aligned

- assets/css/style.css
I have updated the margin of the Wildlife Conservation Forum section from margin: 0 auto to margin: 20px auto. This adjustment improves the visual spacing between the "Wildlife Conservation Forum" section and the adjacent sections, making the layout more readable and aesthetically pleasing.
Changes made:
Modified the margin from 0 auto to 20px auto in the respective CSS/stylesheet file.
How this helps:
Enhances the visual separation between sections.
Improves the readability and overall user experience on the site.
> Changed margin of Wildlife conversation fourm from (0 auto) to (20px auto) #893

- assets/css/style.css
- index.html
Enhance testimonial layout: Increase profile picture size and improve text alignment
- Increased profile picture dimensions from 60px to 80px
- Adjusted testimonial content layout for better vertical alignment
- Refined text styling for improved readability and proportion
- Positioned author info at the bottom for better overall balance
Old Testimonial section:
Updated Testimonial Section:
> Improved the size of the profile picture in the testimonial section and aligned the photo properly with the text and the author name #895

- assets/css/style.css
fixed  what we do text which was blending with background
before
after
Fixes #931
Pls accept this under Hacktoberfest2024.
> Fixes #931 :fixed what we do text which was blending with background

- assets/css/style.css
This pull request implements the proposed feature as described in issue [#956] .The enhancements include custom scrollbar styling across various browsers, ensuring a consistent user experience with a modern, minimalist design.
Scrollbar width set to 9px.
Transparent background for the scrollbar track.
Scrollbar thumb styled with pistachio color and rounded with a 30px radius.
scrollbar-width: thin to make the scrollbar slim.
scrollbar-color: var(--pistachio) transparent for a consistent look.
Applied -ms-overflow-style: -ms-autohiding-scrollbar to enable auto-hiding for a cleaner UI in older IE versions.
This PR addresses #956 
Browsers Tested: Chrome, Firefox, Safari, Edge, Internet Explorer 11,
Testing includes confirming the appearance of scrollbars, the smoothness of scrolling, and …
> [feat] scroller-support-and-enhancement (#956)

- donate.html
fixes : #957 issue 
**Why This Change Is Needed:**
This improves the user experience by ensuring that only valid names can be entered in the form.
It prevents users from accidentally submitting numbers or special characters, which are typically not part of a valid name.
**Testing:**
Verified that the input now only accepts alphabetic characters and spaces.
Ensured that an error message is displayed if the user tries to input invalid characters, and form submission is prevented.
> [fixes]: Restrict Name Input to Alphabetic Characters Only

- assets/css/style.css
This pull request solves the issue where the navbar logo would blend into the background on scroll due to both having the same white color. I have updated the CSS to change the logo color to green when scrolling.
Before:
The logo blends into the background when scrolling, making it invisible:
After:
The logo now changes color to green when scrolling, ensuring it remains visible:
Fix Details:
Added the following CSS to change the logo color when the navbar becomes active on scroll:
.logo {
color: var(--green);
}
Closes Issue: #990
>  Fix Navbar Logo Color on Scroll (#990)

- index.html
#997 clicking on donate now under the support us with you donations section redirects to donation website 
https://github.com/user-attachments/assets/890b030c-1042-4137-aca4-743147ba3f03
added this redirection to all donate now buttons it would be of great help for the users willing to donate so please add this change
> #997 clicking on donate now under the 'support us with your donations' section redirects to donation website

- assets/css/style.css
- assets/js/carousel.js
- index.html
Fixes- #1016 
Before 
User still alerted with Thank you for ur feedback even when input field is empty
https://github.com/user-attachments/assets/9177bc8b-a441-4c83-b83c-c2bb6e348cdc
After
When the user hovers over submit button, the submit word becomes white, which is better suited than black
https://github.com/user-attachments/assets/ce6a5fc3-9e56-475f-a9d0-ec1a744bbdc4
> Fixes- #1016 User alerted with Thank you for ur feedback only when input field not empty

- assets/css/style.css
The "Our Testimonials" section on the website had a significant readability issue due to poor color contrast. The text was displayed in black color against a black background, making it nearly impossible for users to read the testimonials. This problem not only affected user experience but also hindered accessibility for individuals with visual impairments.
Reproduction Steps:
Navigate to the homepage of the website.
Scroll down to the "Our Testimonials" section.
Observe the text color against the background.
Expected Behavior: The text in the "Our Testimonials" section should be clearly visible and easily readable.
Proposed Solution: The text color has been changed from black to green, significantly improving visibility and user experience.
Screenshots:
**BEFORE**
**AFTER**
> "Our Testimonials" Text Not Visible Due to Color Contrast - Issue #1054 Resolved

- SaveEcology.html
In save ecology section, before in the navbar "stats" wasn't linked to its actual page.After the changes it is linked with a modified name "statistics".
> Added navbar link to Statistics section in save ecology page #1123 

- assets/css/style.css
- index.html
I have improved the alignment and structure of service cards . 
I have corrected the positioning of icons , readmore button , text.
I have also improved the service card for large screen size the service cards should come in next line if the screen size is bigger.
Before:
for large screen size 4th card is missing 
After:
for large screen size 4th service card shifts to the next line automatically.
> Improved the structure of service cards #1230

- assets/css/style.css
Previous Implementation of animated made back cover text unable to read as animations works for 2sec. so i created changes so that back cover is shown until the element is hovered.
before
https://github.com/user-attachments/assets/8c2d7e32-e80a-43f6-9590-b72ef7d149b1
after
https://github.com/user-attachments/assets/838c5f27-ddc5-4ef9-b8f7-ed9afd7b5f3e
please add hacktoberfest label.
> Improved Hover Transition in back cover

- index.html
This issue addresses two main changes:
1. **Capitalization**: The "y" in "New York" was incorrectly lowercase, which has been corrected to an uppercase "Y".
2. **Grammar improvement**: The original sentence lacked proper punctuation and flow. Specifically, the phrase **"This hot summer have been"** was changed to **"This hot summer has been"** to correct subject-verb agreement.
- Before: 
- After:
Thank you!
> Fix: Correct capitalization of "Y" in New York and adjust grammar in description

- assets/css/style.css
This PR fixes issue #1433, where the buttons on the second page below the heading "Raise your hands to save world animals life" were causing adjacent components to shift when hovered due to a size change.
Provided a height of '8rem' to the '.tab-nav' div, ensuring the scaling does not affect the other elements position.
Fixed Issue #1433
Browsers Tested: Chrome, Firefox, Safari ,Edge
[ x ] Code readability and structure improved.
[ x ] Grid styling applied to ensure symmetry and alignment.
[ x ] The issue #1433 has been fully addressed.
[ x ] Changes have been tested on various screen sizes.
This change follows the design pattern used across the website, ensuring component reusability and consistency.
> [BugFix ] Resolve button hover animation displacement issue (#1433)

- index.html
- stylesss.css
This PR resolves issue #1435 by adding appropriate spacing between the 'More Events' button and the heart icon. The change ensures better readability and an improved visual layout.
Screenshot
Before
After
> Fix: Add space between 'More Events' button and heart icon (#1435)

- assets/css/style.css
This pull request addresses issue #1461, where the Donation button and the text above it were too close, affecting the visual layout. To resolve this, a margin has been added above the button, ensuring there is sufficient spacing for improved readability and aesthetics.
Screenshots:--
Before:
After:
> Add margin between the Donation button and the line above (#1461)

- Contact.html
The url for the image in the flip.container div had a poor resolution which has been fixed with a new image.
Before:- 
After:-
> Poor resolution of image in flip.container fixed with better image

- index.html
- style_changed.css
Description:
This PR addresses the issue of duplicate "Read More" buttons in the card sections (Save Nature, Save Ecology, Tree Plantation, and Thank You!). The extra button has been removed to streamline the user interface and improve usability. Now, each card contains only one "Read More" button.
Related Issue:
Fixes #1549  - Duplicate "Read More" buttons in all cards.
Changes Made:
Removed the redundant "Read More" button from all cards.
Ensured that each card only has a single, functional "Read More" button.
Before Changes (Screenshot):
After Changes (Screenshot):
> Fix Duplicate "Read More" Buttons in Cards.

- index.html
This PR resolves the issue where the dropdown menu of the profile icon gets hidden behind the "Scroll to Bottom" button when hovered. #1547 
Fixes:
1. Adjusted the z-index of the dropdown menu to ensure it appears above the "Scroll to Bottom" button, allowing the entire content to be fully visible.
2. Tested the hover behavior to ensure smooth interaction and visibility of the dropdown menu.
With this fix, the dropdown menu no longer gets hidden, enhancing the overall user experience.
Before:
After:
> Fix Dropdown Menu Visibility Issue Over Scroll-to-Bottom Button #1547

- assets/css/style.css
This PR addresses an issue #1572  with the "Read More" button in the service section of the `index.html` file. The button previously had an unwanted text-decoration underline, which did not match the design style. The following change was made:
- Removed the` text-decoration underline` from the "Read More" button, setting it to `none` for a cleaner and more professional appearance.
This update enhances the visual consistency of the button and aligns it with the overall styling of the website.
fix issue #1572 
**Before:**
**After:**
**Checklist:**
> fixed issue #1572
